
import React, { useState, useMemo, useEffect, useRef } from 'react';
import { 
  format, 
  addMonths, 
  subMonths, 
  startOfMonth, 
  endOfMonth, 
  startOfISOWeek, 
  endOfISOWeek, 
  eachDayOfInterval, 
  isSameMonth, 
  isSameDay,
  differenceInMinutes
} from 'date-fns';
import { Event, User, AuditLog } from './types';
import { CATEGORIES, CATEGORY_COLORS } from './constants';
import Icon from './components/Icon';
import EventModal from './components/EventModal';
import AdminForm from './components/AdminForm';
import WelcomeScreen from './components/WelcomeScreen';
import AuditModal from './components/AuditModal';
import { notificationService } from './services/notificationService';
import { authService } from './services/authService';
import { supabase } from './services/supabase';

type ViewState = 'welcome' | 'main';

const SQL_SCHEMA = `
-- Run this in your Supabase SQL Editor to initialize Cal tables:

CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT DEFAULT 'admin',
    name TEXT,
    username TEXT,
    email TEXT,
    hashed_password TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    date TIMESTAMPTZ,
    start_time TEXT,
    end_time TEXT,
    poster_url TEXT,
    rsvp_link TEXT,
    location TEXT,
    category TEXT,
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id TEXT,
    admin_name TEXT,
    action TEXT,
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    name TEXT,
    device_id TEXT,
    last_seen TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    event_id TEXT,
    event_time TIMESTAMPTZ,
    notified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, event_id)
);
`;

const App: React.FC = () => {
  const [user, setUser] = useState<User | null>(() => authService.getCurrentSession());
  const [viewState, setViewState] = useState<ViewState>(() => 
    authService.getCurrentSession() ? 'main' : 'welcome'
  );

  const [showAuditDashboard, setShowAuditDashboard] = useState(false);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [globalUserCount, setGlobalUserCount] = useState<number>(0);
  const [showNotificationPrompt, setShowNotificationPrompt] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [isDbSetupNeeded, setIsDbSetupNeeded] = useState(false);
  const [copied, setCopied] = useState(false);
  
  const [darkMode, setDarkMode] = useState(() => {
    const saved = localStorage.getItem('cal-theme');
    return saved === null ? true : saved === 'dark';
  });

  const checkIntervalRef = useRef<number | null>(null);

  useEffect(() => {
    if (user) {
      authService.createSession(user);
      notificationService.syncWithServer(user.id);
      if (notificationService.getPermissionStatus() === 'default') {
        setTimeout(() => setShowNotificationPrompt(true), 3000);
      }
    }
  }, [user]);

  const today = useMemo(() => new Date(), []);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDay, setSelectedDay] = useState<Date>(new Date());
  const [events, setEvents] = useState<Event[]>([]);

  const fetchEvents = async () => {
    setIsLoading(true);
    setFetchError(null);
    setIsDbSetupNeeded(false);
    try {
      const { data, error } = await supabase.from('events').select('*');
      if (error) {
        if (error.message.includes('schema cache') || error.code === '42P01') {
          setIsDbSetupNeeded(true);
          setFetchError("Supabase tables missing.");
        } else {
          setFetchError(error.message);
        }
      } else if (data) {
        const mappedEvents: Event[] = data.map(e => ({
          id: e.id.toString(),
          title: e.title || 'Untitled Event',
          description: e.description || '',
          date: e.date,
          startTime: e.start_time,
          endTime: e.end_time,
          posterUrl: e.poster_url || `https://picsum.photos/seed/${e.id}/600/800`,
          rsvpLink: e.rsvp_link,
          location: e.location,
          category: e.category as any || 'Other',
          color: e.color || '#C28840'
        }));
        setEvents(mappedEvents);
      }
    } catch (e: any) {
      setFetchError(e.message || "Connection failed.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchEvents();
  }, []);

  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);
  const [showAdminForm, setShowAdminForm] = useState(false);
  const [eventToEdit, setEventToEdit] = useState<Event | null>(null);
  const [selectedDateForAdmin, setSelectedDateForAdmin] = useState<Date | undefined>();
  const [showMenu, setShowMenu] = useState(false);
  const [featuredIndex, setFeaturedIndex] = useState(0);

  useEffect(() => {
    const root = window.document.documentElement;
    if (darkMode) {
      root.classList.add('dark');
      localStorage.setItem('cal-theme', 'dark');
    } else {
      root.classList.remove('dark');
      localStorage.setItem('cal-theme', 'light');
    }
  }, [darkMode]);

  useEffect(() => {
    const checkReminders = () => {
      if (notificationService.getPermissionStatus() !== 'granted') return;
      const reminders = notificationService.getReminders();
      const now = new Date();
      Object.entries(reminders).forEach(([eventId, data]) => {
        if (data.notified) return;
        const eventTime = new Date(data.time);
        const diff = differenceInMinutes(eventTime, now);
        if (diff <= 15 && diff > -60) {
          const event = events.find(e => e.id === eventId);
          if (event) {
            notificationService.sendNotification(`Event Starting Soon: ${event.title}`, {
              body: `Starting in ${diff <= 0 ? 'moments' : diff + ' minutes'} at ${event.location || 'the venue'}.`,
              tag: `reminder-${event.id}`
            });
            notificationService.markAsNotified(eventId, user?.id);
          }
        } else if (diff <= -60) {
          notificationService.removeReminder(eventId, user?.id);
        }
      });
    };
    checkIntervalRef.current = window.setInterval(checkReminders, 30000);
    checkReminders();
    return () => { if (checkIntervalRef.current) clearInterval(checkIntervalRef.current); };
  }, [events, user]);

  const handleUserSuccess = (name: string, lastName: string) => {
    const deviceId = authService.getOrCreateDeviceId();
    const formatName = (str: string) => str.trim().split(' ').map(s => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase()).join(' ');
    const capitalizedName = formatName(name);
    const capitalizedLastName = formatName(lastName);
    const newUser: User = {
      id: `user-${deviceId}`,
      role: 'user',
      name: `${capitalizedName} ${capitalizedLastName}`,
      username: capitalizedName.toLowerCase(),
      email: 'user@local'
    };
    authService.createSession(newUser);
    setUser(newUser);
    setViewState('main');
  };

  const handleAdminSuccess = (admin: User) => {
    authService.createSession(admin);
    setUser(admin);
    setViewState('main');
  };

  const handleLogout = () => {
    authService.logout();
    setUser(null);
    setViewState('welcome');
    setShowMenu(false);
    setShowAuditDashboard(false);
  };

  const nextMonth = () => setCurrentDate(addMonths(currentDate, 1));
  const prevMonth = () => setCurrentDate(subMonths(currentDate, 1));

  const days = useMemo(() => {
    const monthStart = startOfMonth(currentDate);
    const monthEnd = endOfMonth(monthStart);
    const calendarStart = startOfISOWeek(monthStart);
    const calendarEnd = endOfISOWeek(monthEnd);
    return eachDayOfInterval({ start: calendarStart, end: calendarEnd });
  }, [currentDate]);

  const eventsInView = useMemo(() => {
    return events
      .filter(e => isSameMonth(new Date(e.date), currentDate))
      .filter(e => !selectedCategory || e.category === selectedCategory)
      .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
  }, [events, currentDate, selectedCategory]);

  useEffect(() => { setFeaturedIndex(0); }, [currentDate, selectedCategory]);

  useEffect(() => {
    if (eventsInView.length <= 1) return;
    const interval = setInterval(() => {
      setFeaturedIndex(prev => (prev + 1) % eventsInView.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [eventsInView]);

  const featuredEvent = useMemo(() => {
    if (eventsInView.length === 0) return null;
    return eventsInView[featuredIndex] || eventsInView[0];
  }, [eventsInView, featuredIndex]);

  const handleAddEvent = async (event: Event) => {
    const posterUrl = event.posterUrl || `https://picsum.photos/seed/${event.id}/600/800`;
    const dbEvent = {
      title: event.title,
      description: event.description,
      date: event.date,
      start_time: event.startTime,
      end_time: event.endTime,
      poster_url: posterUrl,
      rsvp_link: event.rsvpLink,
      location: event.location,
      category: event.category,
      color: event.color
    };
    const { error } = await supabase.from('events').insert(dbEvent);
    if (!error) {
      await fetchEvents();
      if (user && user.role === 'admin') authService.logAction(user, 'Event Added', `Admin added "${event.title}"`);
    }
  };

  const handleUpdateEvent = async (updatedEvent: Event) => {
    const dbEvent = {
      title: updatedEvent.title,
      description: updatedEvent.description,
      date: updatedEvent.date,
      start_time: updatedEvent.startTime,
      end_time: updatedEvent.endTime,
      poster_url: updatedEvent.posterUrl,
      rsvp_link: updatedEvent.rsvpLink,
      location: updatedEvent.location,
      category: updatedEvent.category,
      color: updatedEvent.color
    };
    const { error } = await supabase.from('events').update(dbEvent).eq('id', updatedEvent.id);
    if (!error) {
      await fetchEvents();
      if (user && user.role === 'admin') authService.logAction(user, 'Event Updated', `Admin updated "${updatedEvent.title}"`);
      setEventToEdit(null);
      setSelectedEvent(null);
    }
  };

  const handleDeleteEvent = async (eventId: string) => {
    const eventToDelete = events.find(e => e.id === eventId);
    const { error } = await supabase.from('events').delete().eq('id', eventId);
    if (!error) {
      await fetchEvents();
      if (user && user.role === 'admin' && eventToDelete) authService.logAction(user, 'Event Deleted', `Admin deleted "${eventToDelete.title}"`);
      notificationService.removeReminder(eventId, user?.id);
      setSelectedEvent(null);
    }
  };

  const toggleTheme = () => setDarkMode(!darkMode);

  const requestNotifications = async () => {
    const granted = await notificationService.requestPermission();
    setShowNotificationPrompt(false);
  };

  const handleTestNotification = () => {
    const status = notificationService.getPermissionStatus();
    if (status !== 'granted') {
      requestNotifications();
    } else {
      notificationService.sendNotification("Cal Notification Test", {
        body: "Success! Your event reminders are active and synchronized.",
        tag: "test-notification"
      });
    }
  };

  const openAuditDashboard = async () => {
    const logs = await authService.getAuditLogs();
    setAuditLogs(logs);
    const count = await authService.getGlobalUserCount();
    setGlobalUserCount(count);
    setShowAuditDashboard(true);
  };

  const copySql = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (viewState === 'welcome') {
    return <WelcomeScreen isDark={darkMode} onToggleTheme={toggleTheme} onUserComplete={handleUserSuccess} onAdminComplete={handleAdminSuccess} />;
  }

  return (
    <div className="min-h-screen transition-all duration-500 flex flex-col bg-[#F5F1EB] dark:bg-[#2D3B4D] text-[#517488] dark:text-white font-sans pt-1.5 pb-1.5 px-8 md:pt-5 md:pb-2.5 md:px-12 overflow-x-hidden">
      
      {showNotificationPrompt && (
        <div className="fixed top-0 left-0 right-0 z-[100] bg-[#C28840] text-white py-3 px-6 flex items-center justify-between shadow-lg animate-in slide-in-from-top">
          <div className="flex items-center gap-3">
            <Icon name="BellRing" size={20} />
            <p className="text-sm font-bold">Enable notifications for event alerts?</p>
          </div>
          <div className="flex gap-4">
            <button onClick={() => setShowNotificationPrompt(false)} className="text-xs font-bold opacity-70">Later</button>
            <button onClick={requestNotifications} className="bg-white text-[#C28840] px-4 py-1.5 rounded-full text-xs font-bold">Enable</button>
          </div>
        </div>
      )}

      <header className="flex items-center justify-between mb-2 max-w-2xl mx-auto w-full">
        <span className="text-3xl md:text-4xl font-black tracking-tighter text-[#517488] dark:text-[#C28840]">Cal</span>
        <button onClick={() => setShowMenu(!showMenu)} className="relative group">
          <div className="w-10 h-10 bg-[#C28840] text-white rounded-full flex items-center justify-center font-bold shadow-md group-hover:scale-110 transition-transform">
            {user?.name?.charAt(0).toUpperCase()}
          </div>
          {isDbSetupNeeded && (
             <div className="absolute -top-1 -right-1 w-3 h-3 bg-red-500 rounded-full border-2 border-white"></div>
          )}
        </button>
      </header>

      {isDbSetupNeeded && (
        <div className="max-w-2xl mx-auto w-full mb-6 p-6 bg-red-500/10 border border-red-500/30 rounded-[24px] animate-in slide-in-from-top duration-500">
          <div className="flex items-start gap-4">
            <div className="p-3 bg-red-500 rounded-2xl text-white shadow-lg shadow-red-500/20">
              <Icon name="Database" size={24} />
            </div>
            <div className="flex-1">
              <h4 className="text-lg font-black text-red-500 uppercase tracking-tight">Database Required</h4>
              <p className="text-sm font-medium dark:text-slate-300 mt-1 leading-relaxed">
                The Cal database tables were not found in Supabase. Shared events, cross-device sync, and audit logs are currently disabled.
              </p>
              <div className="flex gap-3 mt-4">
                <button onClick={copySql} className={`px-5 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${copied ? 'bg-green-500 text-white' : 'bg-red-500 text-white hover:bg-red-600'}`}>
                  {copied ? 'SQL Copied!' : 'Copy SQL Script'}
                </button>
                <button onClick={fetchEvents} className="px-5 py-2 border border-red-500/30 rounded-xl text-xs font-black uppercase tracking-widest text-red-500 hover:bg-red-500/5">
                  Retry Connection
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <section className="mb-6">
        <div 
          onClick={() => !isLoading && !isDbSetupNeeded && featuredEvent && setSelectedEvent(featuredEvent)}
          className="bg-[#DCE7EF] dark:bg-[#DCE7EF] rounded-[12px] p-5 shadow-2xl flex items-center gap-8 cursor-pointer transition-transform active:scale-[0.98] border border-white/40 max-w-2xl mx-auto w-full overflow-hidden relative min-h-[140px]"
        >
          {isLoading ? (
            <div className="flex-1 flex flex-col items-center justify-center gap-2 opacity-30">
              <Icon name="Loader2" className="animate-spin" size={32} />
              <p className="text-[10px] font-bold uppercase tracking-widest">Connecting...</p>
            </div>
          ) : (
            <>
              <div className="w-28 h-28 md:w-44 md:h-44 flex-shrink-0 rounded-[12px] overflow-hidden shadow-md">
                <img src={featuredEvent?.posterUrl || "https://picsum.photos/seed/cal/300/300"} className="w-full h-full object-cover" />
              </div>
              <div className="flex-1">
                <p className="text-[#2D3B4D] text-lg md:text-xl font-bold leading-tight">
                  {featuredEvent?.description || (isDbSetupNeeded ? "Please complete database setup." : "No upcoming events yet.")}
                </p>
                {featuredEvent?.location && (
                  <div className="mt-2 flex items-center gap-2 text-xs font-bold text-[#517488]/70 uppercase tracking-widest">
                    <Icon name="MapPin" size={14} /> {featuredEvent.location}
                  </div>
                )}
              </div>
              {featuredEvent && (
                <div className="absolute bottom-4 right-4 w-3.5 h-3.5 rounded-full border-2 border-white/50" style={{ backgroundColor: featuredEvent.color }} />
              )}
            </>
          )}
        </div>
      </section>

      <section className="mb-6 w-full max-w-2xl mx-auto overflow-x-auto no-scrollbar">
        <div className="flex items-center gap-3 py-2">
          <button onClick={() => setSelectedCategory(null)} className={`px-6 py-2 rounded-full text-sm font-bold transition-all border ${!selectedCategory ? 'bg-[#517488] text-white border-transparent' : 'border-[#517488]/20 dark:border-white/20'}`}>All</button>
          {CATEGORIES.map(cat => (
            <button key={cat} onClick={() => setSelectedCategory(cat === selectedCategory ? null : cat)} style={{ backgroundColor: selectedCategory === cat ? CATEGORY_COLORS[cat] : 'transparent', color: selectedCategory === cat ? 'white' : undefined }} className={`px-6 py-2 rounded-full text-sm font-bold transition-all border ${selectedCategory === cat ? 'border-transparent shadow-lg' : 'border-[#517488]/20 dark:border-white/20'}`}>
              {cat}
            </button>
          ))}
        </div>
      </section>

      <section className="flex-grow flex flex-col items-center">
        <div className="grid grid-cols-7 w-full max-w-xl mb-4 border-b border-[#517488]/10 pb-4">
          {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => (
            <div key={d} className="text-center text-xs font-bold opacity-40 uppercase tracking-widest">{d}</div>
          ))}
        </div>
        <div className="grid grid-cols-7 w-full max-w-xl gap-y-2">
          {days.map((day, idx) => {
            const isCurrentMonth = isSameMonth(day, currentDate);
            const isSelected = isSameDay(day, selectedDay);
            const dayEvents = events.filter(e => isSameDay(new Date(e.date), day) && (!selectedCategory || e.category === selectedCategory));
            return (
              <div key={idx} className="flex flex-col items-center justify-center relative h-10 w-full">
                {isSameDay(day, today) && <div className="absolute inset-0 m-auto w-8 h-8 bg-[#517488]/10 rounded-lg"></div>}
                <button onClick={() => { setSelectedDay(day); if (!isCurrentMonth) setCurrentDate(startOfMonth(day)); if (dayEvents.length > 0) setSelectedEvent(dayEvents[0]); }} className={`text-lg font-bold transition-all relative z-10 ${!isCurrentMonth ? 'opacity-20' : isSelected ? 'scale-110' : 'hover:opacity-70'}`}>
                  {format(day, 'd')}
                  {dayEvents.length > 0 && <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-3 h-0.5 rounded-full" style={{ backgroundColor: dayEvents[0].color }} />}
                </button>
              </div>
            );
          })}
        </div>
      </section>

      <footer className="mt-auto mb-8 flex flex-col items-center gap-6">
        <div className="flex items-center justify-center gap-12 w-full max-w-xl">
          <button onClick={prevMonth} className="p-2 opacity-50 hover:opacity-100"><Icon name="ChevronLeft" size={28}/></button>
          <div className="text-center">
            <div className="text-2xl font-black tracking-tight">{format(currentDate, 'MMMM')}</div>
            <div className="text-[10px] font-bold text-[#C28840] uppercase tracking-[0.2em]">{format(currentDate, 'yyyy')}</div>
          </div>
          <button onClick={nextMonth} className="p-2 opacity-50 hover:opacity-100"><Icon name="ChevronRight" size={28}/></button>
        </div>
        {user?.role === 'admin' && !isDbSetupNeeded && (
          <button onClick={() => { setSelectedDateForAdmin(selectedDay); setShowAdminForm(true); }} className="px-8 py-4 bg-[#C28840] text-white rounded-full shadow-2xl font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all flex items-center gap-2">
            <Icon name="Plus" size={18} /> Add Event
          </button>
        )}
      </footer>

      {showMenu && (
        <div className="fixed inset-0 z-[110] flex justify-end">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-md" onClick={() => setShowMenu(false)}></div>
          <div className="relative w-80 h-full bg-[#EFEDE7] dark:bg-[#1E293B] shadow-2xl p-10 animate-in slide-in-from-right duration-300">
            <div className="flex items-center justify-between mb-12">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-[#C28840] rounded-2xl flex items-center justify-center text-white font-black text-xl shadow-lg">{user?.name?.charAt(0)}</div>
                <div>
                  <h2 className="text-lg font-black dark:text-white leading-tight">{user?.name}</h2>
                  <p className="text-[10px] font-bold text-[#C28840] uppercase tracking-widest">{user?.role}</p>
                </div>
              </div>
              <button onClick={() => setShowMenu(false)} className="p-2 dark:text-white"><Icon name="X" size={28}/></button>
            </div>
            
            <div className="space-y-4">
               <button onClick={toggleTheme} className="w-full text-left font-bold flex items-center gap-4 p-4 hover:bg-black/5 dark:hover:bg-white/5 rounded-2xl transition-all">
                 <Icon name={darkMode ? "Sun" : "Moon"} size={20} /> {darkMode ? 'Light Mode' : 'Dark Mode'}
               </button>
               <button onClick={handleTestNotification} className="w-full text-left font-bold flex items-center gap-4 p-4 hover:bg-black/5 dark:hover:bg-white/5 rounded-2xl transition-all text-[#C28840]">
                 <Icon name="BellRing" size={20} /> Test Notification
               </button>
               {user?.role === 'admin' && (
                 <>
                   <button onClick={openAuditDashboard} className="w-full text-left font-bold flex items-center gap-4 p-4 hover:bg-black/5 dark:hover:bg-white/5 rounded-2xl transition-all">
                     <Icon name="Activity" size={20} /> Audit Logs
                   </button>
                   <div className="p-4 bg-black/5 dark:bg-white/5 rounded-2xl flex items-center justify-between">
                     <div className="flex items-center gap-3 font-bold text-sm">
                       <Icon name="Users" size={18} className="text-[#C28840]" /> Global Members
                     </div>
                     <span className="text-lg font-black text-[#C28840]">{globalUserCount}</span>
                   </div>
                 </>
               )}
               <button onClick={handleLogout} className="w-full mt-12 py-4 bg-black/5 dark:bg-white/10 rounded-2xl font-black uppercase tracking-widest text-xs transition-all hover:bg-red-500 hover:text-white">Exit Cal</button>
            </div>
          </div>
        </div>
      )}

      <EventModal event={selectedEvent} onClose={() => setSelectedEvent(null)} isAdmin={user?.role === 'admin'} onDelete={handleDeleteEvent} onEdit={(e) => { setEventToEdit(e); setShowAdminForm(true); }} />
      <AuditModal isOpen={showAuditDashboard} onClose={() => setShowAuditDashboard(false)} logs={auditLogs} />
      {showAdminForm && <AdminForm onAdd={handleAddEvent} onUpdate={handleUpdateEvent} onClose={() => { setShowAdminForm(false); setSelectedDateForAdmin(undefined); setEventToEdit(null); }} initialDate={selectedDateForAdmin} eventToEdit={eventToEdit} />}
    </div>
  );
};

export default App;
